### ISSUE TITLE
Where is the source?

### ISSUE THREAD

**Issue by ralt** [stumpwm/stumpwm.github.io#2]
Hi,

Is there a source for this repository? It looks like only the generated code is committed there.

Cheers,
Florian

**Comment by fstamour** [comment]
The source is there: https://github.com/stumpwm/stumpwm

There are some instructions on how it was generated, here: https://github.com/stumpwm/stumpwm.github.io/pull/3#issue-449463625

Finally, here is the lisp code that generates the texinfo documentation (which is then used to generate pdf, html, etc): https://github.com/stumpwm/stumpwm/blob/05ec1a92bd4d4a81f2dff023cbf9916982157a6d/manual.lisp

**Comment by dmb2** [comment]
Sorry for the uncomfortably long reply.  This repo is both the source and the html files.  Its written in Emacs's org-mode and processead by emacs in batch mode.

The manuals are also generated using texi2pdf and texi2html from the stumpwm source.  At this point the only non-automated build part is when we tag new releases.
